<a href="https://colab.research.google.com/github/Nasreen69/Python/blob/main/Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Random***

In [ ]:
import random as ra
v = ra.sample(range(11,66),6)
w = ra.randrange(4,14,2)
x = chr(ra.randrange(ord('A'), ord('Z')+1)) 
y = chr(ra.randrange(ord('a'), ord('z')+1))
z = ra.randint(11,66)
k = ra.choice(v)
print(v)
print(w)
print(x)
print(y)
print(z)
print(k)

[41, 45, 11, 31, 52, 51]
12
A
w
31
31


# ***Regular Expression***

## [RegEx](https://www.w3schools.com/python/python_regex.asp)

### *MetaChar*


| Char  | Description | Example
|  ----     |     ----    |  ----  |
| ( )| Capture's enclosed Group of all regex 
| [ ]| Represent a set of character's class | "[a-z]"
| { }| Exactly the specified number of occurances | "fix{1}"
| .  | Any character except newline character | "us..o"
| *  | 0 or more occurance | "bix*"
| ^  | Starts with/matches beginning | "Mrs."
| $  | Ends with/matches the end | "Singh"
| ?  | matches 0 or 1 occurences
| +  | 1 or more occurance | "bix+"
| \  | A special sequence. Also used to escape special characters | "\s"
| \| |Either or | "fruit\|flower"
| \w | Matches any word character |  ""

 

### *Spec-Seq*


| Char  | Description | Example
|  ----     |     ----    |  ----  |
| r |  Placed in beginning of string treated as raw | r"\brain"
| \A | returns a match of Specific char at beginning  | "\ANas"
| \b | returns a match of Specific char present at start/end|r"\brain",r"rain\b"
| \B | returns a match of Specific char present but NOT at start/end |r"\Brain",r"rain\B"
| \d | returns a match where contains digits from 0-9 | "\d"
| \D | returns a match where DOES NOT contains digits | "\D"
| \s | returns a match where contains a whitespace char | "\s"
| \S | returns a match where DOES NOT contains a whitespace char | "\S"
| \w | returns a match where contains any word chars(from a-z, A-Z, 0-9) | "\w"
| \W | returns a match where DOES NOT contains any chars | "\W"
| \Z | returns a match if specified chars at end of string | "fruit\|flower"


 



*https?://\S+*

`The ? quantifier makes the preceding s character optional, allowing the pattern to match URLs that start with either http or https.`

`The + quantifier in \S+ matches one or more non-whitespace characters, whereas the {2} quantifier in \S{2} matches exactly two non-whitespace characters.`

*\w+@\w+\.\w{2,3}*

`\w matches any word char(letter,digit,or underscore) {2,3} means should be matched between 2 and 3 times`

*\[a-z0-9]*

`set of small_chars and digits`



### *Functions*

- `findall()`

- `search()`

- `split()`

- `sub()`

## *Info*

In [ ]:
import re 

In [ ]:
Password = "Nasreen66"
Sentence = "Nasreen is DataScientist in google"
mail = 'armaan.malik@gmail.com'
web_urls = 'www.google.com'
soc_urls = 'https://www.linkedin.com/company/aksprotalent/'

In [ ]:
d_find = re.findall('\d{1,6}', Password)
d_search = re.search('\d', Password) 
d_match = re.match('\D[a-z]{1,9}', Password)  #re.match('\D{1,9}', Password) 
b_find = re.findall(r'\bNas', Password)  #start char of string
b_search = re.search(r'\Been', Password)  #any char of string 
w_find = re.findall('\w+', Password)  # re.findall('\w', Password) 
w_search = re.search('\w+', Password) 
w_match = re.match('\w+', Password) 

In [ ]:
print(d_find,'\n',d_search, '\n', d_match  )
print(b_find,'\n', b_search, '\n')
print(w_find,'\n', w_search, '\n',w_match)
print()

['66'] 
 <re.Match object; span=(7, 8), match='6'> 
 <re.Match object; span=(0, 7), match='Nasreen'>
['Nas'] 
 <re.Match object; span=(4, 7), match='een'> 

['Nasreen66'] 
 <re.Match object; span=(0, 9), match='Nasreen66'> 
 <re.Match object; span=(0, 9), match='Nasreen66'>



In [ ]:
mail_search = re.search('@', mail)
mail_search1 = re.search(r'^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$', mail)
mail_search2 = re.search('\w+\.\w+@\w+\.\w{2,3}', mail)
mail_find = re.findall('@', mail)
mail_find1 = re.findall(r'^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$', mail)
mail_find2 = re.findall('\w+\.\w+@\w+\.\w{2,3}', mail)

In [ ]:
mail_split = re.split("\s", mail)

In [ ]:
print("Search function:\n", mail_search,'\n', mail_search1,'\n', mail_search2,'\n')
print("findall function:\n",mail_find,'\n', mail_find1,'\n', mail_find2,'\n')

Search function:
 <re.Match object; span=(12, 13), match='@'> 
 <re.Match object; span=(0, 22), match='armaan.malik@gmail.com'> 
 <re.Match object; span=(0, 22), match='armaan.malik@gmail.com'> 

findall function:
 ['@'] 
 ['armaan.malik@gmail.com'] 
 ['armaan.malik@gmail.com'] 



In [ ]:
url_search = re.search('https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+', soc_urls) 

In [ ]:
print(url_search)

<re.Match object; span=(0, 24), match='https://www.linkedin.com'>


In [ ]:
WEB_URL_logic= r"""(?i)\b((?:https?:(?:/{1,3}|[a-z0-9%])|[a-z0-9.\-]+[.](?:com|net|org|edu|gov|mil|aero|in|co)\b/?(?!@)))"""

# ***String***

In [ ]:
import string
alno =  string.ascii_lowercase + ':\n' + string.ascii_uppercase + ':\n' + string.ascii_letters + ':\n' + string.digits
print(alno)

abcdefghijklmnopqrstuvwxyz:
ABCDEFGHIJKLMNOPQRSTUVWXYZ:
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ:
0123456789


# ***Numpy***

`Task 1: Create array without using NumPy`


In [ ]:
arr1 = []
limit = int(input("enter your limit of array : "))
for i in range(limit):
    elements = int(input(" enter your elements of the array :"))
    arr1.append(elements)
      # or
arr2 = [int(x) for x in input().replace("'", "").split(",")[0].split()]

arr3 = "[" + " ".join(str(x) for x in arr1) + "]"
print(arr3, type(arr3),max(arr1), min(arr1))
print(arr2)

enter your limit of array : 11
 enter your elements of the array :1
 enter your elements of the array :3
 enter your elements of the array :5
 enter your elements of the array :7
 enter your elements of the array :9
 enter your elements of the array :2
 enter your elements of the array :5
 enter your elements of the array :4
 enter your elements of the array :6
 enter your elements of the array :8
 enter your elements of the array :9
1 3 6 9 7 3 2 8 0
[1 3 5 7 9 2 5 4 6 8 9] <class 'str'> 9 1
[1, 3, 6, 9, 7, 3, 2, 8, 0]


`Task 2: Create a NumPy array`

In [ ]:
import numpy as np

In [ ]:
arr3 = np.array (np.arange(1301, 2302))
arr4 = np.array([2,3,7])
arr5 = np.array([[10,20,30],[40,50,60]])
arr6 = np.empty([2,2], dtype=int)  #dtype=complex
arr7 = np.full((2,3), 5) #shape and value
arr8 = np.zeros([2,3])
arr9 = np.ones([3,5]) 
arr10 = np.eye(5) #returns an array of identical matrix of size 5X5
arr11 = np.linspace(0, 20, 5) #Returns a Linearly-Spaced Vector spacing

array([1301, 1302, 1303, ..., 2299, 2300, 2301])

In [ ]:
l = []
for i in range(1,11):
  l.append(i)

arr = np.array(l)  
print(arr) 
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
print(arr3, arr4, arr5, arr6, arr7, arr8, arr9, arr10, arr11)
print(type(arr3), type(arr4), type(arr5), type(arr6), type(arr7), type(arr8), type(arr9), type(arr10), type(arr11))

array([2, 3, 7])

`*Attributes*`

In [ ]:
arr3.shape
arr3.size
arr3.ndim

`Task 3: Indexing and Slicing in NumPy`

In [ ]:
#Indexing 
a = np.arange(1,10)
print("Accessed Element:", a[5], a[3:], a[1:7:2] ) #Accessing a Single Element

Accessed Element: 6


In [ ]:
b = np.array([[2,4,5],[6,8,1],[4,1,6],[9,1,4]])
slice1 = slice(2,7,2)  #slice() function to access multiple elements
print(b[slice1])
print(b[2:7:2]) 
print(b[0:3,0:2], b[:3,:], b[:,:2]) #slicing 1st 3 rows & 2 columns #slicing 1st 3 rows #Slicing 1st 2 columns 

In [ ]:
print("Min & Max & Mean along axis-0:\n", np.amin(b), np.amax(b), np.mean(b,0))
print("Min & Max & Mean along axis-1:\n", np.amin(b,1), np.amax(b,1), np.mean(b,1))
print("Mean, median, std_dev, min:\n", b.mean(), b.std(), np.median(b), b.min())

In [ ]:
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)

In [ ]:
arr = [7.52, 21.58, 42.81, 43.72, 14.23, 32.64, 51.91, 2.50, 1.99] 
print("Input array : \n",arr) 

print ("\nRounded values : \n",np.around(arr)) 
print ("\nRounded values after decimal 1 : \n",np.around(arr,1)) 
print ("\nRounded values before decimal 1: \n",np.around(arr,-1))
print (np.floor(arr))
print (np.ceil(arr))

# ***pandas***

### csv file

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Titanic-Dataset.csv')  # read_excel(), read_json(), read_html(), read_sql(), read_pickle()

In [ ]:
df.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [ ]:
df.tail(4)

PassengerId  Survived  Pclass                                      Name  \
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
deep =  df.copy(deep=True)
print (deep is False)
print (deep is True)

False
False


In [ ]:
shallow = df.copy(deep=False) 
print (shallow is False)
print (shallow is True)

False
False


In [ ]:
df.shape    #size of dataset 

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
len(df.columns)

12

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.dtypes.value_counts()

int64      5
object     5
float64    2
dtype: int64

In [ ]:
df.select_dtypes(include=['object'])[:4]

Name     Sex  \
0                            Braund, Mr. Owen Harris    male   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                             Heikkinen, Miss. Laina  female   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   

             Ticket Cabin Embarked  
0         A/5 21171   NaN        S  
1          PC 17599   C85        C  
2  STON/O2. 3101282   NaN        S  
3            113803  C123        S

In [ ]:
df.value_counts().values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1])

In [ ]:
df.value_counts()[:4].index

MultiIndex([(  2, 1, 1, ...),
            (572, 1, 1, ...),
            (578, 1, 1, ...),
            (582, 1, 1, ...)],
           names=['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'])

In [ ]:
df.isnull().sum()  #used to detect missing values and return dataframe

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.isna().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [ ]:
df.isnull().any()     

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.sort_values(by=['Age'], axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')[:4]

PassengerId  Survived  Pclass                             Name     Sex  \
803          804         1       3  Thomas, Master. Assad Alexander    male   
755          756         1       2        Hamalainen, Master. Viljo    male   
644          645         1       3           Baclini, Miss. Eugenie  female   
469          470         1       3    Baclini, Miss. Helene Barbara  female   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
803  0.42      0      1    2625   8.5167   NaN        C  
755  0.67      1      1  250649  14.5000   NaN        S  
644  0.75      2      1    2666  19.2583   NaN        C  
469  0.75      2      1    2666  19.2583   NaN        C

In [ ]:
df.nunique () #method searches column-wise and returns the number of unique values for each row.

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [ ]:
df.mean()

<ipython-input-83-c61f0c8f89b5>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [ ]:
df.median()

<ipython-input-84-6d467abf240d>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()


PassengerId    446.0000
Survived         0.0000
Pclass           3.0000
Age             28.0000
SibSp            0.0000
Parch            0.0000
Fare            14.4542
dtype: float64

In [ ]:
df.std()

<ipython-input-85-ce97bb7eaef8>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()


PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
import numpy as np
df.describe(include=[np.number])

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
df.describe(include=[np.object])

<ipython-input-58-554b7518cb2b>:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df.describe(include=[np.object])


Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
df.describe().T.head(4)

count        mean         std   min      25%    50%    75%    max
PassengerId  891.0  446.000000  257.353842  1.00  223.500  446.0  668.5  891.0
Survived     891.0    0.383838    0.486592  0.00    0.000    0.0    1.0    1.0
Pclass       891.0    2.308642    0.836071  1.00    2.000    3.0    3.0    3.0
Age          714.0   29.699118   14.526497  0.42   20.125   28.0   38.0   80.0